import { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
const money = v => new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format((Number(v)||0)/100);
const api = async (path, token, options={}) => { const r = await fetch(`/api${path}`, { ...options, headers: { 'Content-Type':'application/json', Authorization:`Bearer ${token}`, ...(options.headers||{}) } }); if(!r.ok) throw new Error((await r.json()).error || 'Request failed'); return r.status===204 ? null : r.json(); };
const modules = {
 dashboard:{label:'Dashboard'}, companies:{label:'CRM Companies', fields:['name','domain','industry','phone','address','status']}, contacts:{label:'Contacts', fields:['company_id','first_name','last_name','email','phone','title']}, leads:{label:'Leads', fields:['company_id','source','status','estimated_value_minor','notes']}, opportunities:{label:'Sales Pipeline', fields:['company_id','name','stage','deal_value_minor','probability','expected_close_date']}, quotes:{label:'Quotes', fields:['opportunity_id','quote_number','status','subtotal_minor','tax_minor','total_minor','valid_until']}, projects:{label:'Projects', fields:['company_id','opportunity_id','name','status','priority','budget_minor','estimated_cost_minor','actual_cost_minor','progress','due_date']}, tasks:{label:'Tasks', fields:['project_id','title','status','assignee','due_date']}, tickets:{label:'Helpdesk', fields:['company_id','project_id','subject','priority','status','internal_notes','sla_due_at']}, invoices:{label:'Invoices', fields:['company_id','project_id','invoice_number','status','subtotal_minor','tax_minor','total_minor','due_date']}, payments:{label:'Payments', fields:['invoice_id','amount_minor','method','reference']}, activities:{label:'Activity Timeline', fields:['company_id','opportunity_id','project_id','ticket_id','invoice_id','type','body']} };
function App(){ const [token,setToken]=useState(localStorage.token||''); const [email,setEmail]=useState('admin@mortify.local'); const [password,setPassword]=useState('ChangeMe123!'); const [page,setPage]=useState('dashboard'); const [error,setError]=useState('');
 async function login(e){ e.preventDefault(); setError(''); try{ const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})}).then(r=>r.json()); if(r.token){ localStorage.token=r.token; setToken(r.token); } else setError(r.error); } catch(e){ setError(e.message); } }
 if(!token) return <main className="login"><form onSubmit={login} className="login-card"><p className="eyebrow">Modular Business CRM</p><h1>Mortify CRM Suite</h1><input value={email} onChange={e=>setEmail(e.target.value)} /><input type="password" value={password} onChange={e=>setPassword(e.target.value)} /><button>Sign in</button>{error&&<p className="error">{error}</p>}</form></main>;
 return <div className="shell"><aside><h2>Mortify CRM</h2>{Object.entries(modules).map(([k,m])=><button className={page===k?'active':''} onClick={()=>setPage(k)} key={k}>{m.label}</button>)}<button onClick={()=>{localStorage.removeItem('token');setToken('')}}>Sign out</button></aside><main><header><div><p className="eyebrow">Lead → Payment operating system</p><h1>{modules[page].label}</h1></div></header>{page==='dashboard'?<Dashboard token={token}/>:<Resource token={token} name={page} config={modules[page]} setPage={setPage}/>}</main></div> }
function Dashboard({token}){ const [data,setData]=useState(); useEffect(()=>{api('/dashboard',token).then(setData)},[token]); if(!data) return <p>Loading dashboard…</p>; return <><section className="grid"><Card title="Total pipeline" value={money(data.pipelineValueMinor)}/><Card title="Won revenue" value={money(data.wonRevenueMinor)}/><Card title="Open projects" value={data.openProjects.length}/><Card title="Overdue tickets" value={data.overdueTickets.length}/><Card title="Outstanding invoices" value={data.outstandingInvoices.length}/><Card title="Latest margin" value={money(data.projectMargins.reduce((a,p)=>a+Number(p.margin_minor||0),0))}/></section><section className="columns"><Panel title="Open projects" rows={data.openProjects.map(p=>`${p.name} — ${p.status} — ${p.progress}% — margin ${money(p.budget_minor-p.actual_cost_minor)}`)}/><Panel title="Outstanding invoices" rows={data.outstandingInvoices.map(i=>`${i.invoice_number} — ${money(i.outstanding_minor)} due ${i.due_date}`)}/><Panel title="SLA risks" rows={data.overdueTickets.map(t=>`${t.subject} — ${t.priority} — ${new Date(t.sla_due_at).toLocaleString()}`)}/></section></> }
function Resource({token,name,config,setPage}){ const [rows,setRows]=useState([]), [meta,setMeta]=useState({}), [form,setForm]=useState({}), [search,setSearch]=useState(''), [error,setError]=useState(''); const load=()=>Promise.all([api(`/resources/${name}?search=${encodeURIComponent(search)}`,token),api('/meta',token)]).then(([r,m])=>{setRows(r);setMeta(m)}).catch(e=>setError(e.message)); useEffect(()=>{load()},[name]);
 const refs = useMemo(()=>({company_id:meta.companies, opportunity_id:meta.opportunities, project_id:meta.projects, invoice_id:meta.invoices, assigned_user_id:meta.users}),[meta]);
 async function submit(e){ e.preventDefault(); setError(''); try{ await api(`/resources/${name}`,token,{method:'POST',body:JSON.stringify(form)}); setForm({}); load(); }catch(e){setError(e.message)} }
 async function convert(id){ await api(`/opportunities/${id}/convert-to-project`,token,{method:'POST',body:'{}'}); setPage('projects'); }
 return <><section className="toolbar"><input placeholder="Search by main name…" value={search} onChange={e=>setSearch(e.target.value)} /><button onClick={load}>Search</button></section>{error&&<p className="error">{error}</p>}<form className="panel form-grid" onSubmit={submit}>{config.fields.map(f=> refs[f]?<select key={f} value={form[f]||''} onChange={e=>setForm({...form,[f]:e.target.value})}><option value="">{label(f)}</option>{refs[f]?.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select>:<input key={f} placeholder={label(f)} value={form[f]||''} onChange={e=>setForm({...form,[f]:e.target.value})}/>)}<button>Create {config.label}</button></form><section className="table panel"><table><thead><tr>{headers(rows).map(h=><th key={h}>{label(h)}</th>)}{name==='opportunities'&&<th>Action</th>}</tr></thead><tbody>{rows.map(r=><tr key={r.id}>{headers(rows).map(h=><td key={h}>{cell(h,r[h])}</td>)}{name==='opportunities'&&<td><button onClick={()=>convert(r.id)}>Convert won</button></td>}</tr>)}</tbody></table></section></> }
function headers(rows){ return Object.keys(rows[0]||{}).filter(k=>!k.endsWith('_hash')).slice(0,10); }
function label(s){ return s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase()); }
function cell(k,v){ if(v==null) return '—'; if(k.endsWith('_minor')) return money(v); if(String(v).match(/^\d{4}-\d{2}-\d{2}T/)) return new Date(v).toLocaleDateString(); return String(v); }
function Card({title,value}){return <article className="card"><span>{title}</span><strong>{value}</strong></article>}
function Panel({title,rows=[]}){return <section className="panel"><h2>{title}</h2><ul>{rows.length?rows.map((x,i)=><li key={i}>{x}</li>):<li>No records</li>}</ul></section>}
createRoot(document.getElementById('root')).render(<App/>);
