import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
const api = (path, token, options={}) => fetch(`/api${path}`, { ...options, headers: { 'Content-Type':'application/json', Authorization:`Bearer ${token}`, ...(options.headers||{}) } }).then(r => r.json());
function App(){ const [token,setToken]=useState(localStorage.token||''); const [email,setEmail]=useState('admin@mortify.local'); const [password,setPassword]=useState('ChangeMe123!'); const [data,setData]=useState(null); const [integrations,setIntegrations]=useState({});
 async function login(e){ e.preventDefault(); const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})}).then(r=>r.json()); if(r.token){ localStorage.token=r.token; setToken(r.token); } }
 async function report(){ await api('/ai/report',token,{method:'POST',body:JSON.stringify({kind:'daily_briefing'})}); load(); }
 async function load(){ setData(await api('/dashboard',token)); setIntegrations(await api('/integrations',token)); }
 useEffect(()=>{ if(token) load(); },[token]); if(!token) return <main className="login"><form onSubmit={login}><h1>Mortify Co-Director</h1><input value={email} onChange={e=>setEmail(e.target.value)} /><input type="password" value={password} onChange={e=>setPassword(e.target.value)} /><button>Sign in</button></form></main>;
 return <main><header><h1>Mortify Co-Director</h1><button onClick={report}>Generate CEO Briefing</button></header><section className="grid"><Card title="Revenue" value={`£${data?.revenue?.toLocaleString()||0}`} /><Card title="Outstanding Invoices" value={data?.outstandingInvoices?.length||0} /><Card title="Active Projects" value={data?.activeProjects?.length||0} /><Card title="Server Health" value={data?.serverHealth?.[0]?.status||'No alerts'} /></section><section className="panel"><h2>Daily briefing</h2><pre>{JSON.stringify(data?.dailyBriefing||'Generate a briefing to begin.',null,2)}</pre></section><section className="columns"><List title="Projects" items={data?.activeProjects?.map(p=>`${p.name} — ${p.progress}% — priority ${p.priority}`)} /><List title="Invoices" items={data?.outstandingInvoices?.map(i=>`${i.invoice_number}: £${i.amount} due ${i.due_date}`)} /><List title="Integrations" items={Object.entries(integrations).map(([k,v])=>`${k}: ${v.configured?'configured':'pending'}`)} /></section></main> }
function Card({title,value}){return <article className="card"><span>{title}</span><strong>{value}</strong></article>}
function List({title,items=[]}){return <section className="panel"><h2>{title}</h2><ul>{items.map((x,i)=><li key={i}>{x}</li>)}</ul></section>}
createRoot(document.getElementById('root')).render(<App/>);
