import express from 'express';
import bcrypt from 'bcryptjs';
import { query } from '../db/pool.js';
import { requireAuth, signToken } from '../middleware/auth.js';
import { getDashboard } from '../services/dashboard.js';
import { generateDirectorReport, remember } from '../ai/director.js';
import { checkDisk, checkDocker, checkSsl, checkWebsite } from '../services/monitoring.js';
import { integrations } from '../integrations/index.js';
export const api = express.Router();
api.post('/auth/login', async (req,res)=>{ const { email, password } = req.body; const { rows } = await query('SELECT * FROM users WHERE email=$1',[email]); const user = rows[0]; if (!user || !(await bcrypt.compare(password, user.password_hash))) return res.status(401).json({ error:'Invalid credentials' }); res.json({ token: signToken(user), user: { email:user.email, role:user.role } }); });
api.use(requireAuth);
api.get('/dashboard', async (_req,res)=>res.json(await getDashboard()));
api.get('/integrations', (_req,res)=>res.json(integrations));
api.post('/ai/report', async (req,res)=>res.status(201).json(await generateDirectorReport(req.body.kind || 'management_report')));
api.post('/ai/memory', async (req,res)=>res.status(201).json(await remember(req.body.memoryType, req.body.subject, req.body.content, req.body.metadata)));
api.get('/reports', async (_req,res)=>{ const { rows } = await query('SELECT * FROM reports ORDER BY created_at DESC LIMIT 50'); res.json(rows); });
api.get('/projects', async (_req,res)=>{ const { rows } = await query('SELECT * FROM projects ORDER BY priority,due_date'); res.json(rows); });
api.get('/invoices', async (_req,res)=>{ const { rows } = await query('SELECT * FROM invoices ORDER BY due_date'); res.json(rows); });
api.post('/monitoring/run', async (req,res)=>{ const results = [await checkDisk(), await checkDocker()]; if (req.body.website) results.push(await checkWebsite(req.body.website)); if (req.body.sslHost) results.push(await checkSsl(req.body.sslHost)); res.status(201).json(results); });
