import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import compression from 'compression';
import morgan from 'morgan';
import rateLimit from 'express-rate-limit';
import cron from 'node-cron';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { collectDefaultMetrics, register } from 'prom-client';
import { config } from './config.js';
import { api } from './routes/api.js';
import { generateDirectorReport } from './ai/director.js';
collectDefaultMetrics();
const app = express();
app.use(helmet({ contentSecurityPolicy: false })); app.use(cors({ origin: config.corsOrigin, credentials: true })); app.use(compression()); app.use(express.json({ limit: '1mb' })); app.use(morgan('combined')); app.use(rateLimit({ windowMs: 60_000, limit: 300 }));
app.get('/health', (_req,res)=>res.json({ status:'ok', service:'mortify-co-director' })); app.get('/metrics', async (_req,res)=>{ res.set('Content-Type', register.contentType); res.end(await register.metrics()); }); app.use('/api', api);
const dist = path.join(path.dirname(fileURLToPath(import.meta.url)), '../../client/dist'); app.use(express.static(dist)); app.get('*', (_req,res)=>res.sendFile(path.join(dist,'index.html')));
cron.schedule('0 7 * * *', () => generateDirectorReport('daily_briefing').catch(console.error));
app.listen(config.port, () => console.log(`Mortify Co-Director listening on ${config.port}`));
